import httpx

with open("proxies.txt", 'w') as file:
	print("Proxies Scraper")
	file.write(httpx.get("https://api.proxyscrape.com/v2/?request=getproxies&protocol=http&timeout=10000&country=all&ssl=all&anonymity=anonymous").text)
	file.write(httpx.get("https://raw.githubusercontent.com/TheSpeedX/PROXY-List/master/http.txt").text)
	file.write(httpx.get("https://raw.githubusercontent.com/ShiftyTR/Proxy-List/master/http.txt").text)
	file.write(httpx.get("https://raw.githubusercontent.com/ShiftyTR/Proxy-List/master/https.txt").text)
	file.write(httpx.get("https://api.proxyscrape.com/?request=displayproxies&proxytype=socks5").text)
	file.write(httpx.get("https://api.proxyscrape.com/v2/?request=displayproxies&protocol=socks5").text)
	file.write(httpx.get("https://api.proxyscrape.com/v2/?request=getproxies&protocol=socks5&timeout=10000&country=all&simplified=true").text)
	file.write(httpx.get("https://www.proxyscan.io/download?type=http").text)
	file.write(httpx.get("https://www.proxyscan.io/download?type=https").text)
	file.write(httpx.get("https://raw.githubusercontent.com/mmpx12/proxy-list/master/https.txt").text)
	file.write(httpx.get("https://proxyspace.pro/http.txt").text)
	file.write(httpx.get("https://api.proxyscrape.com/?request=displayproxies&proxytype=http").text)
	file.write(httpx.get("https://www.proxy-list.download/api/v1/get?type=http").text)
	file.write(httpx.get("https://raw.githubusercontent.com/monosans/proxy-list/main/proxies/http.txt").text)
        file.write(httpx.get(file.write(httpx.get("http://worm.rip/socks4.txtfile.write(httpx.get(").text)
        file.write(httpx.get(file.write(httpx.get("http://worm.rip/socks5.txtfile.write(httpx.get(").text)
        file.write(httpx.get(file.write(httpx.get("http://worm.rip/http.txtfile.write(httpx.get(").text)
        file.write(httpx.get(file.write(httpx.get("https://sheesh.rip/all.txtfile.write(httpx.get(").text)
        file.write(httpx.get(file.write(httpx.get("http://alexa.lr2b.com/proxylist.txtfile.write(httpx.get(").text)
        file.write(httpx.get(file.write(httpx.get("https://www.proxy-list.download/api/v1/get?type=socks4file.write(httpx.get(").text)
        file.write(httpx.get(file.write(httpx.get("https://www.proxy-list.download/api/v1/get?type=socks5file.write(httpx.get(").text)
        file.write(httpx.get(file.write(httpx.get("https://www.proxy-list.download/api/v1/get?type=httpfile.write(httpx.get(").text)
        file.write(httpx.get("https://api.openproxylist.xyz/http.txtfile.write(httpx.get(").text)
        file.write(httpx.get("https://api.openproxylist.xyz/socks4.txtfile.write(httpx.get(").text)
        file.write(httpx.get("https://api.openproxylist.xyz/socks5.txtfile.write(httpx.get(").text)
        file.write(httpx.get("http://rootjazz.com/proxies/proxies.txtfile.write(httpx.get(").text)
        file.write(httpx.get("https://multiproxy.org/txt_all/proxy.txtfile.write(httpx.get(").text)
        file.write(httpx.get("https://proxy-spider.com/api/proxies.example.txtfile.write(httpx.get(").text)
        file.write(httpx.get("https://raw.githubusercontent.com/TheSpeedX/PROXY-List/master/http.txtfile.write(httpx.get(").text)
        file.write(httpx.get("https://raw.githubusercontent.com/TheSpeedX/PROXY-List/master/socks4.txtfile.write(httpx.get(").text)
        file.write(httpx.get("https://raw.githubusercontent.com/TheSpeedX/PROXY-List/master/socks5.txtfile.write(httpx.get(").text)
        file.write(httpx.get("https://raw.githubusercontent.com/jetkai/proxy-list/main/online-proxies/txt/proxies.txtfile.write(httpx.get(").text)
        file.write(httpx.get("https://raw.githubusercontent.com/RX4096/proxy-list/main/archive/all.txtfile.write(httpx.get(").text)
        file.write(httpx.get("https://raw.githubusercontent.com/mertguvencli/http-proxy-list/main/proxy-list/data.txtfile.write(httpx.get(").text)
        file.write(httpx.get("https://raw.githubusercontent.com/UptimerBot/proxy-list/main/proxies/http.txtfile.write(httpx.get(").text)
        file.write(httpx.get("https://raw.githubusercontent.com/UptimerBot/proxy-list/main/proxies/socks4.txtfile.write(httpx.get(").text)
        file.write(httpx.get("https://raw.githubusercontent.com/UptimerBot/proxy-list/main/proxies/socks5.txtfile.write(httpx.get(").text)
        file.write(httpx.get("https://raw.githubusercontent.com/ShiftyTR/Proxy-List/master/http.txtfile.write(httpx.get(").text)
        file.write(httpx.get("https://raw.githubusercontent.com/ShiftyTR/Proxy-List/master/https.txtfile.write(httpx.get(").text)
        file.write(httpx.get("https://raw.githubusercontent.com/ShiftyTR/Proxy-List/master/socks4.txtfile.write(httpx.get(").text)
        file.write(httpx.get("https://raw.githubusercontent.com/ShiftyTR/Proxy-List/master/socks5.txtfile.write(httpx.get(").text)
        file.write(httpx.get("https://raw.githubusercontent.com/ShiftyTR/Proxy-List/master/proxy.txtfile.write(httpx.get(").text)
        file.write(httpx.get("https://raw.githubusercontent.com/hookzof/socks5_list/master/proxy.txtfile.write(httpx.get(").text)
        file.write(httpx.get("https://raw.githubusercontent.com/clarketm/proxy-list/master/proxy-list-raw.txtfile.write(httpx.get(").text)
        file.write(httpx.get("https://raw.githubusercontent.com/sunny9577/proxy-scraper/master/proxies.txtfile.write(httpx.get(").text)
        file.write(httpx.get("https://raw.githubusercontent.com/opsxcq/proxy-list/master/list.txtfile.write(httpx.get(").text)
        file.write(httpx.get("https://raw.githubusercontent.com/roosterkid/openproxylist/main/SOCKS5_RAW.txtfile.write(httpx.get(").text)
        file.write(httpx.get("https://raw.githubusercontent.com/roosterkid/openproxylist/main/SOCKS4_RAW.txtfile.write(httpx.get(").text)
        file.write(httpx.get("https://raw.githubusercontent.com/roosterkid/openproxylist/main/HTTPS_RAW.txtfile.write(httpx.get(").text)
        file.write(httpx.get("https://api.proxyscrape.com/v2/?request=getproxies&protocol=http&timeout=10000&country=all&ssl=all&anonymity=allfile.write(httpx.get(").text)
        file.write(httpx.get("https://api.proxyscrape.com/v2/?request=getproxies&protocol=socks4&timeout=10000&country=all&ssl=all&anonymity=allfile.write(httpx.get(").text)
        file.write(httpx.get("https://api.proxyscrape.com/v2/?request=getproxies&protocol=socks5&timeout=10000&country=all&ssl=all&anonymity=allfile.write(httpx.get(").text)
	
